package main

import (
	"fmt"
	"net/http"
)

const css = `
*{box-sizing:border-box}
:root{color-scheme:dark;--bg:#07070a;--panel:#101116;--panel2:#15161d;--line:#252733;--text:#f7f7fb;--muted:#8e93a5;--accent:#7c5cff;--good:#35d07f}
body{margin:0;background:var(--bg);color:var(--text);font:14px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.shell{min-height:100vh;display:flex}.side{position:fixed;inset:0 auto 0 0;width:245px;padding:18px 16px;border-right:3px solid #111;background:#ffe45e;z-index:5}
.brand{display:flex;align-items:center;gap:10px;padding:8px 10px 28px;font-size:19px;font-weight:800}.logo{width:34px;height:34px;border:3px solid #111;background:#111;color:#fff;display:grid;place-items:center;font-weight:950;box-shadow:4px 4px 0 #fff}
.nav{display:grid;gap:5px}.nav a{display:flex;gap:11px;align-items:center;padding:12px;border:3px solid #111;background:#fffdf5;color:#111;text-decoration:none;font-weight:850;box-shadow:4px 4px 0 #111}.nav a:hover,.nav .on{transform:translate(2px,2px);box-shadow:2px 2px 0 #111;background:#fff;color:#111}.bottom{position:absolute;bottom:18px;left:16px;right:16px;color:var(--muted);font-size:12px}
.main{margin-left:245px;max-width:1250px;width:100%;padding:34px 38px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px}.eyebrow{color:#9b8cff;font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.title{margin:5px 0 4px;font-size:28px;letter-spacing:-.03em}.muted{color:var(--muted)}.actions{display:flex;gap:9px}.btn{border:1px solid var(--line);background:var(--panel2);color:#fff;padding:10px 14px;border-radius:10px;text-decoration:none;font-weight:650}.btn.primary{background:var(--accent);border-color:var(--accent)}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:28px}.card{background:#fffdf5;border:3px solid #111;border-radius:0;padding:19px;box-shadow:7px 7px 0 #111}.label{color:var(--muted);font-size:12px;font-weight:650}.value{font-size:27px;font-weight:800;margin-top:9px;letter-spacing:-.03em}.status{display:inline-flex;align-items:center;gap:7px}.dot{width:7px;height:7px;border-radius:50%;background:var(--good);box-shadow:0 0 12px #35d07f}
.section{margin-top:18px}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.section h2{font-size:15px;margin:0}.table{padding:4px 18px}.row{display:flex;justify-content:space-between;gap:18px;padding:15px 0;border-bottom:1px solid var(--line)}.row:last-child{border:0}.pill{padding:5px 8px;border:2px solid #111;background:#8df58d;color:#111;font-size:11px;font-weight:900}
@media(max-width:820px){.side{position:static;width:100%;height:auto;border-right:0;border-bottom:1px solid var(--line);padding:12px}.shell{display:block}.brand{padding:4px 6px 12px}.nav{display:flex;overflow:auto}.nav a{white-space:nowrap}.bottom{display:none}.main{margin-left:0;padding:22px 15px}.grid{grid-template-columns:1fr}.top{align-items:flex-start}.actions{display:none}}
`

func dashboard(w http.ResponseWriter){
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	html := `<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='theme-color' content='#07070a'><title>Axy Router — SaaS Gateway</title><style>` + css + `</style></head><body><div class='shell'><aside class='side'><div class='brand'><span class='logo'>A</span>Axy Router</div><nav class='nav'><a class='on' href='/'>⌂ <span>Overview</span></a><a href='/providers'>◆ <span>Providers</span></a><a href='/'>◇ <span>Models</span></a><a href='/'>⌘ <span>API Keys</span></a><a href='/'>≡ <span>Logs</span></a><a href='/'>⚙ <span>Settings</span></a></nav><div class='bottom'>SaaS Gateway · v1.0</div></aside><main class='main'><div class='top'><div><div class='eyebrow'>Control Center</div><h1 class='title'>Good to see you.</h1><div class='muted'>Manage your AI gateway from one clean workspace.</div></div><div class='actions'><a class='btn' href='/api/health'>Health</a><form method='post' action='/logout'><button class='btn'>Logout</button></form></div></div><div class='grid'><div class='card'><div class='label'>Gateway status</div><div class='value status'><i class='dot'></i>Online</div></div><div class='card'><div class='label'>Connected providers</div><div class='value' id='providers'>—</div></div><div class='card'><div class='label'>API endpoint</div><div class='value'>Ready</div></div></div><section class='section'><div class='section-head'><h2>Provider overview</h2><span class='muted'>Live configuration</span></div><div class='card table'><div id='list' class='muted'>Loading providers…</div></div></section></main></div><script>fetch('/api/providers').then(r=>r.json()).then(x=>{document.querySelector('#providers').textContent=x.providers.length;document.querySelector('#list').innerHTML=x.providers.length?x.providers.map(p=>'<div class="row"><div><b>'+p.name+'</b><div class="muted">'+p.base_url+'</div></div><div><span class="pill">'+(p.enabled?'Enabled':'Disabled')+'</span><div class="muted" style="margin-top:5px;text-align:right">'+p.model+'</div></div></div>').join(''):'No providers configured yet.'}).catch(()=>document.querySelector('#list').textContent='Unable to load providers.')</script></body></html>`
	fmt.Fprint(w, html)
}

func(s *Server)providerPage(w http.ResponseWriter,r *http.Request){
	if !s.authed(r){http.Redirect(w,r,"/login",302);return}
	w.Header().Set("Content-Type","text/html; charset=utf-8")
	html := "<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><title>Axy Router — Providers</title><style>"+css+".form{display:grid;gap:12px}.form input{width:100%;padding:12px;border:3px solid #111;background:#fff;color:#111;font:inherit;box-sizing:border-box}.form button{padding:12px 16px;border:3px solid #111;background:#ff79c8;color:#111;font-weight:900;box-shadow:4px 4px 0 #111;cursor:pointer}.provider{display:flex;justify-content:space-between;gap:16px;padding:15px 0;border-bottom:2px solid #111}.provider:last-child{border-bottom:0}</style></head><body><div class='shell'><aside class='side'><div class='brand'><span class='logo'>A</span>Axy Router</div><nav class='nav'><a href='/'>▣ <span>Overview</span></a><a class='on' href='/providers'>◆ <span>Providers</span></a><a href='/'>◇ <span>Models</span></a><a href='/'>⌘ <span>API Keys</span></a><a href='/'>≡ <span>Logs</span></a><a href='/'>⚙ <span>Settings</span></a></nav><div class='bottom'>NEOBRUTAL CONTROL · v1.0</div></aside><main class='main'><div class='top'><div><div class='eyebrow'>Provider Manager</div><h1 class='title'>Providers.</h1><div class='muted'>Connect and manage your AI backends.</div></div><div class='actions'><a class='btn' href='/'>← Overview</a></div></div><section class='section'><div class='card'><h2 style='margin-top:0'>Add provider</h2><form class='form' id='f'><input name='name' placeholder='Provider name' required><input name='base_url' placeholder='https://api.example.com/v1' required><input name='api_key' type='password' placeholder='API key' required><input name='model' placeholder='Model ID' required><button>Save provider →</button></form></div></section><section class='section'><div class='section-head'><h2>Configured providers</h2><span class='muted' id='count'>Loading…</span></div><div class='card' id='list'>Loading providers…</div></section></main></div><script>function load(){fetch('/api/providers').then(r=>r.json()).then(x=>{document.getElementById('count').textContent=x.providers.length+' configured';document.getElementById('list').innerHTML=x.providers.length?x.providers.map(p=>'<div class="provider"><div><b>'+p.name+'</b><div class="muted">'+p.base_url+'</div></div><div><span class="pill">'+(p.enabled?'Enabled':'Disabled')+'</span><div class="muted">'+p.model+'</div></div></div>').join(''):'No providers configured yet.'})}document.getElementById('f').onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(e.target));let r=await fetch('/api/providers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});if(r.ok){e.target.reset();load()}else alert('Failed to save provider')};load()</script></body></html>"
	fmt.Fprint(w,html)
}

func loginPage(w http.ResponseWriter, msg string){
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	html := fmt.Sprintf(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Axy Router — Sign in</title><style>`+css+`.login{min-height:100vh;display:grid;place-items:center;padding:20px}.login-card{width:min(410px,100%);padding:30px;border:1px solid var(--line);border-radius:20px;background:rgba(16,17,22,.92)}.login-card h1{margin:0;font-size:25px}.login-card p{color:var(--muted)}input,button{width:100%;font:inherit}input{padding:13px 14px;border-radius:11px;border:1px solid var(--line);background:#090a0e;color:#fff;outline:none}button{margin-top:10px;padding:13px;border:0;border-radius:11px;background:var(--accent);color:#fff;font-weight:750;cursor:pointer}.error{color:#ff7777!important;font-size:13px}</style></head><body><main class="login"><form class="login-card" method="post"><div class="brand" style="padding:0 0 20px"><span class="logo">A</span>Axy Router</div><h1>Welcome back</h1><p>Enter your admin PIN to access the gateway.</p><input name="pin" type="password" inputmode="numeric" maxlength="12" autofocus placeholder="Admin PIN"><button>Sign in</button><p class="error">%s</p></form></main></body></html>`, msg)
	fmt.Fprint(w, html)
}
