package main

import (
	"fmt"
	"net/http"
)

const css = `
:root{--bg:#ffffff;--paper:#ffffff;--soft:#f7f7f5;--ink:#181818;--muted:#6f6f6f;--line:#deded8;--accent:#ffd84d;--pink:#ff9bd5;--cyan:#bcefff;--green:#bdf2c1}
body{margin:0;background:var(--bg);color:var(--ink);font:14px Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.shell{min-height:100vh;display:flex}.side{position:fixed;inset:0 auto 0 0;width:245px;padding:20px 16px;border-right:1px solid var(--line);background:#fff;z-index:5}
.brand{display:flex;align-items:center;gap:10px;padding:7px 8px 24px;font-size:20px;font-weight:850}.logo{width:34px;height:34px;border:2px solid var(--ink);background:var(--accent);color:var(--ink);display:grid;place-items:center;font-weight:950;box-shadow:3px 3px 0 var(--ink)}
.nav{display:grid;gap:7px}.nav a{display:flex;gap:11px;align-items:center;padding:11px 12px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);text-decoration:none;font-weight:750;transition:.15s}.nav a:hover,.nav .on{background:var(--soft);border-color:#c8c8c0;transform:translateX(2px);box-shadow:3px 3px 0 #e8e8e2}.bottom{position:absolute;bottom:18px;left:16px;right:16px;color:var(--muted);font-size:12px}
.main{margin-left:245px;max-width:1250px;width:100%;padding:34px 38px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px}.eyebrow{color:#8a7000;font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.title{margin:5px 0 4px;font-size:30px;letter-spacing:-.035em}.muted{color:var(--muted)}.actions{display:flex;gap:9px}.btn{border:1px solid var(--ink);background:#fff;color:var(--ink);padding:10px 14px;border-radius:9px;text-decoration:none;font-weight:800;box-shadow:3px 3px 0 #deded8;cursor:pointer}.btn:hover{transform:translate(1px,1px);box-shadow:2px 2px 0 #deded8}.btn.primary{background:var(--accent)}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:28px}.card{background:var(--paper);border:1px solid var(--line);border-radius:12px;padding:19px;box-shadow:4px 4px 0 #f0f0ec}.label{color:var(--muted);font-size:12px;font-weight:700}.value{font-size:27px;font-weight:850;margin-top:9px;letter-spacing:-.03em}.status{display:inline-flex;align-items:center;gap:7px}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);border:1px solid #70b875}
.section{margin-top:20px}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.section h2{font-size:15px;margin:0;font-weight:800}.table{padding:4px 18px}.row{display:flex;justify-content:space-between;gap:18px;padding:15px 0;border-bottom:1px solid var(--line)}.row:last-child{border:0}.pill{padding:5px 8px;border-radius:7px;background:var(--green);border:1px solid #8dce91;font-size:11px;font-weight:800}
@media(max-width:820px){.side{position:static;width:100%;height:auto;border-right:0;border-bottom:1px solid var(--line);padding:12px}.shell{display:block}.brand{padding:4px 6px 12px}.nav{display:flex;overflow:auto}.nav a{white-space:nowrap}.bottom{display:none}.main{margin-left:0;padding:22px 15px}.grid{grid-template-columns:1fr}.top{align-items:flex-start}.actions{display:none}}

`

func dashboard(w http.ResponseWriter){
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	html := `<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='theme-color' content='#07070a'><title>Axy Router — SaaS Gateway</title><style>` + css + `</style></head><body><div class='shell'><aside class='side'><div class='brand'><span class='logo'>A</span>Axy Router</div><nav class='nav'><a class='on' href='/'>⌂ <span>Overview</span></a><a href='/providers'>◆ <span>Providers</span></a><a href='/'>◇ <span>Models</span></a><a href='/'>⌘ <span>API Keys</span></a><a href='/'>≡ <span>Logs</span></a><a href='/'>⚙ <span>Settings</span></a></nav><div class='bottom'>SaaS Gateway · v1.0</div></aside><main class='main'><div class='top'><div><div class='eyebrow'>Control Center</div><h1 class='title'>Good to see you.</h1><div class='muted'>Manage your AI gateway from one clean workspace.</div></div><div class='actions'><a class='btn' href='/api/health'>Health</a><form method='post' action='/logout'><button class='btn'>Logout</button></form></div></div><div class='grid'><div class='card'><div class='label'>Gateway status</div><div class='value status'><i class='dot'></i>Online</div></div><div class='card'><div class='label'>Connected providers</div><div class='value' id='providers'>—</div></div><div class='card'><div class='label'>API endpoint</div><div class='value'>Ready</div></div></div><section class='section'><div class='section-head'><h2>Provider overview</h2><span class='muted'>Live configuration</span></div><div class='card table'><div id='list' class='muted'>Loading providers…</div></div></section></main></div><script>fetch('/api/providers').then(r=>r.json()).then(x=>{document.querySelector('#providers').textContent=x.providers.length;document.querySelector('#list').innerHTML=x.providers.length?x.providers.map(p=>'<div class="row"><div><b>'+p.name+'</b><div class="muted">'+p.base_url+'</div></div><div><span class="pill">'+(p.enabled?'Enabled':'Disabled')+'</span><div class="muted" style="margin-top:5px;text-align:right">'+p.model+'</div></div></div>').join(''):'No providers configured yet.'}).catch(()=>document.querySelector('#list').textContent='Unable to load providers.')</script></body></html>`
	fmt.Fprint(w, html)
}

func(s *Server)providerPage(w http.ResponseWriter,r *http.Request){
	if !s.authed(r){http.Redirect(w,r,"/login",302);return}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	html := `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Axy Router — Providers</title><style>` + css + `
.provider-wrap{display:grid;gap:24px}.provider-toolbar{display:flex;justify-content:space-between;align-items:center;gap:14px}.provider-tabs{display:flex;gap:7px;overflow:auto}.tab{padding:8px 12px;border:1px solid var(--line);border-radius:9px;background:#fff;font-weight:800;white-space:nowrap}.tab.active{background:var(--ink);color:#fff;border-color:var(--ink)}
.connection-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.connection{background:#fff;border:1px solid var(--line);border-radius:13px;padding:18px;box-shadow:4px 4px 0 #f0f0ec}.connection-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.provider-icon{width:42px;height:42px;border:1px solid var(--ink);border-radius:10px;background:var(--accent);display:grid;place-items:center;font-weight:950;font-size:18px;box-shadow:3px 3px 0 var(--ink)}.provider-name{font-size:16px;font-weight:900;margin-top:2px}.provider-type{font-size:12px;color:var(--muted);margin-top:3px}.connection-meta{display:grid;gap:8px;margin:16px 0}.meta-line{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-bottom:1px solid #eee}.meta-line:last-child{border-bottom:0}.meta-key{color:var(--muted);font-size:12px}.meta-value{font-weight:750;text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.provider-actions{display:flex;gap:8px}.small-btn{border:1px solid var(--ink);background:#fff;color:var(--ink);padding:8px 10px;border-radius:8px;font-weight:800;cursor:pointer}.small-btn.primary{background:var(--accent)}.empty{padding:34px;text-align:center;border:1px dashed #cfcfc8;border-radius:12px;color:var(--muted);background:#fff}.add-panel{display:none;background:#fff;border:1px solid var(--line);border-radius:13px;padding:18px;box-shadow:4px 4px 0 #f0f0ec}.add-panel.open{display:block}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form input{width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:9px;background:#fff;color:#111;font:inherit;box-sizing:border-box}.form .full{grid-column:1/-1}.form button{padding:11px 15px;border:1px solid var(--ink);border-radius:9px;background:var(--accent);color:#111;font-weight:900;box-shadow:3px 3px 0 #deded8;cursor:pointer}.section-label{font-size:13px;font-weight:900;margin-bottom:10px}.secret{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}
@media(max-width:820px){.connection-grid{grid-template-columns:1fr}.form{grid-template-columns:1fr}.form .full{grid-column:auto}.provider-toolbar{align-items:flex-start;flex-direction:column}.provider-actions{flex-wrap:wrap}}
</style></head><body><div class="shell"><aside class="side"><div class="brand"><span class="logo">A</span>Axy Router</div><nav class="nav"><a href="/">▣ <span>Overview</span></a><a class="on" href="/providers">◆ <span>Providers</span></a><a href="/">◇ <span>Models</span></a><a href="/">⌘ <span>API Keys</span></a><a href="/">≡ <span>Logs</span></a><a href="/">⚙ <span>Settings</span></a></nav><div class="bottom">Axy Gateway · v1.0</div></aside><main class="main"><div class="top"><div><div class="eyebrow">Connections</div><h1 class="title">Providers</h1><div class="muted">Connect API providers and manage the backends used by Axy Router.</div></div><div class="actions"><a class="btn" href="/">← Overview</a></div></div><div class="provider-wrap" style="margin-top:24px"><div class="provider-toolbar"><div class="provider-tabs"><span class="tab active">All</span><span class="tab">API Key</span><span class="tab">Custom</span></div><button class="btn primary" id="addBtn" type="button">＋ Add connection</button></div><div class="add-panel" id="panel"><div class="section-label">Add connection</div><form class="form" id="f"><input name="name" placeholder="Provider name" required><input name="model" placeholder="Model ID" required><input class="full" name="base_url" placeholder="https://api.example.com/v1" required><input class="full" name="api_key" type="password" placeholder="API key" required><button class="full">Save connection</button></form></div><section><div class="section-head"><h2>Connected providers</h2><span class="muted" id="count">Loading…</span></div><div class="connection-grid" id="list"></div></section></div></main></div><script>
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function icon(n){return esc((n||"A").trim().charAt(0).toUpperCase())}
function load(){fetch("/api/providers").then(r=>r.json()).then(x=>{document.getElementById("count").textContent=x.providers.length+" configured";const list=document.getElementById("list");if(!x.providers.length){list.innerHTML='<div class="empty" style="grid-column:1/-1"><b>No providers connected</b><div style="margin-top:6px">Add your first OpenAI-compatible backend to get started.</div></div>';return}list.innerHTML=x.providers.map(p=>'<article class="connection"><div class="connection-head"><div style="display:flex;gap:12px;align-items:center"><div class="provider-icon">'+icon(p.name)+'</div><div><div class="provider-name">'+esc(p.name)+'</div><div class="provider-type">API Key · OpenAI compatible</div></div></div><span class="pill">'+(p.enabled?'Connected':'Disabled')+'</span></div><div class="connection-meta"><div class="meta-line"><span class="meta-key">Base URL</span><span class="meta-value">'+esc(p.base_url)+'</span></div><div class="meta-line"><span class="meta-key">Model</span><span class="meta-value">'+esc(p.model)+'</span></div><div class="meta-line"><span class="meta-key">API key</span><span class="meta-value secret">••••••••</span></div></div><div class="provider-actions"><button class="small-btn primary" type="button" onclick="alert(\'Provider test endpoint akan ditambahkan berikutnya.\')">Test</button><button class="small-btn" type="button" onclick="alert(\'Edit provider akan ditambahkan berikutnya.\')">Edit</button></div></article>').join("")}).catch(()=>document.getElementById("list").innerHTML='<div class="empty">Unable to load providers.</div>')}
document.getElementById("addBtn").onclick=()=>document.getElementById("panel").classList.toggle("open");
document.getElementById("f").onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(e.target));let r=await fetch("/api/providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});if(r.ok){e.target.reset();document.getElementById("panel").classList.remove("open");load()}else alert("Failed to save provider")};
load();
</script></body></html>`
	fmt.Fprint(w,html)
}

func loginPage(w http.ResponseWriter, msg string){
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	html := fmt.Sprintf(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Axy Router — Sign in</title><style>`+css+`.login{min-height:100vh;display:grid;place-items:center;padding:20px}.login-card{width:min(410px,100%);padding:30px;border:1px solid var(--line);border-radius:20px;background:rgba(16,17,22,.92)}.login-card h1{margin:0;font-size:25px}.login-card p{color:var(--muted)}input,button{width:100%;font:inherit}input{padding:13px 14px;border-radius:11px;border:1px solid var(--line);background:#090a0e;color:#fff;outline:none}button{margin-top:10px;padding:13px;border:0;border-radius:11px;background:var(--accent);color:#fff;font-weight:750;cursor:pointer}.error{color:#ff7777!important;font-size:13px}</style></head><body><main class="login"><form class="login-card" method="post"><div class="brand" style="padding:0 0 20px"><span class="logo">A</span>Axy Router</div><h1>Welcome back</h1><p>Enter your admin PIN to access the gateway.</p><input name="pin" type="password" inputmode="numeric" maxlength="12" autofocus placeholder="Admin PIN"><button>Sign in</button><p class="error">%s</p></form></main></body></html>`, msg)
	fmt.Fprint(w, html)
}
